=== Smile-SA/elasticsuite/src/module-elasticsuite-core/etc/elasticsuite_indices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Smile_ElasticsuiteCore indices configuration validation.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer
 * versions in the future.
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteCore
 * @author    Aurelien FOUCRET <aurelien.foucret@smile.fr>
 * @author    Romain RUAUD <romain.ruaud@smile.fr>
 * @copyright 2020 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="indices">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="index" type="indexDefinition" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="indexDefinition">
        <xs:sequence>
            <xs:element name="type" maxOccurs="unbounded" minOccurs="0" type="typeDefinition"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="identifier" use="optional"/>
        <xs:attribute type="xs:string" name="defaultSearchType" use="optional"/>
    </xs:complexType>

    <xs:complexType name="typeDefinition">
        <xs:all>
            <xs:element name="datasources" type="datasourcesDefinition" minOccurs="0"/>
            <xs:element name="mapping" type="mappingDefinition"/>
        </xs:all>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="idFieldName" use="required"/>
    </xs:complexType>

    <xs:complexType name="datasourcesDefinition">
        <xs:sequence maxOccurs="unbounded" minOccurs="1">
            <xs:element name="datasource" type="datasourceDefinition" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="datasourceDefinition">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="mappingDefinition">
        <xs:annotation>
            <xs:documentation>
                Mapping declaration root node
            </xs:documentation>
        </xs:annotation>
        <xs:choice maxOccurs="unbounded" minOccurs="1">
            <xs:element name="field" type="fieldDefinition"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="fieldDefinition">
        <xs:annotation>
            <xs:documentation>Mapping field declaration root node</xs:documentation>
        </xs:annotation>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:any processContents="lax" />
        </xs:choice>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="nestedPath" use="optional"/>
    </xs:complexType>
</xs:schema>

=== Smile-SA/elasticsuite/src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml
<?xml version="1.0"?>
<!--
/**
 * Smile_ElasticsuiteCatalog indices configuration.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer
 * versions in the future.
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteCatalog
 * @author    Aurelien FOUCRET <aurelien.foucret@smile.fr>
 * @copyright 2020 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
 -->
<indices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:Smile_ElasticsuiteCore:etc/elasticsuite_indices.xsd">

    <index identifier="catalog_product" defaultSearchType="product">
        <type name="product" idFieldName="entity_id">
            <mapping>
                <!-- Static fields handled by the base indexer (not datasource) -->
                <field name="entity_id" type="integer" />
                <field name="attribute_set_id" type="integer" />
                <field name="has_options" type="boolean" />
                <field name="required_options" type="boolean" />
                <field name="created_at" type="date" />
                <field name="updated_at" type="date" />
                <field name="type_id" type="keyword" />
                <field name="sku" type="text">
                    <isSearchable>1</isSearchable>
                    <isUsedForSortBy>1</isUsedForSortBy>
                    <isUsedInSpellcheck>1</isUsedInSpellcheck>
                    <isFilterable>1</isFilterable>
                    <defaultSearchAnalyzer>reference</defaultSearchAnalyzer>
                </field>
                <field name="visibility" type="integer" />
                <field name="children_ids" type="integer" />
                <field name="configurable_attributes" type="keyword" />
                <field name="indexed_attributes" type="keyword" />
                <field name="is_saleable" type="integer" />

                <!-- Static fields handled by the "prices" datasource -->
                <field name="price.price" type="double" nestedPath="price" />
                <field name="price.original_price" type="double" nestedPath="price" />
                <field name="price.is_discount" type="boolean" nestedPath="price" />
                <field name="price.customer_group_id" type="integer" nestedPath="price" />
                <field name="price.tax_class_id" type="integer" nestedPath="price" />
                <field name="price.final_price" type="double" nestedPath="price" />
                <field name="price.min_price" type="double" nestedPath="price" />
                <field name="price.max_price" type="double" nestedPath="price" />

                <!-- Static fields handled by the "stock" datasource -->
                <field name="stock.is_in_stock" type="boolean" />
                <field name="stock.qty" type="integer" />

                <!-- Static fields handled by the "categories" datasource -->
                <field name="category.category_id" type="integer" nestedPath="category" />
                <field name="category.category_uid" type="text" nestedPath="category" />
                <field name="category.position" type="integer" nestedPath="category" />
                <field name="category.is_parent" type="boolean" nestedPath="category" />
                <field name="category.name" type="text" nestedPath="category">
                    <isSearchable>1</isSearchable>
                    <isUsedInSpellcheck>1</isUsedInSpellcheck>
                    <isFilterable>0</isFilterable>
                </field>

                <!-- Static fields handled by the "searchPositions" datasource -->
                <field name="search_query.query_id" type="integer" nestedPath="search_query" />
                <field name="search_query.position" type="integer" nestedPath="search_query" />
                <field name="search_query.is_blacklisted" type="boolean" nestedPath="search_query" />

            </mapping>
        </type>
    </index>

    <index identifier="catalog_category" defaultSearchType="category">
        <type name="category" idFieldName="entity_id">
            <mapping>
                <!-- Static fields handled by the base indexer (not datasource) -->
                <field name="entity_id" type="integer" />
                <field name="attribute_set_id" type="integer" />
                <field name="parent_id" type="integer" />
                <field name="created_at" type="date" />
                <field name="updated_at" type="date" />
                <field name="path" type="keyword" />
                <field name="position" type="integer" />
                <field name="level" type="integer" />
                <field name="children_count" type="integer" />
                <field name="is_displayed_in_autocomplete" type="boolean" />
            </mapping>
        </type>
    </index>

</indices>

=== Smile-SA/elasticsuite/src/module-elasticsuite-tracker/etc/elasticsuite_indices.xml
<?xml version="1.0"?>
<!--
/**
 * Smile_ElasticsuiteCatalog indices configuration.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer
 * versions in the future.
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteTracker
 * @author    Aurelien FOUCRET <aurelien.foucret@smile.fr>
 * @copyright 2020 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
 -->
<indices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:Smile_ElasticsuiteCore:etc/elasticsuite_indices.xsd">

    <index identifier="tracking_log_event" defaultSearchType="event">
        <type name="event" idFieldName="event_id">
            <mapping>
                <!-- Event metadata -->
                <field name="event_id" type="keyword" />
                <field name="date" type="date" />

                <!-- Session data -->
                <field name="session.uid" type="keyword" />
                <field name="session.vid" type="keyword" />

                <!-- Page metadata -->
                <field name="page.site" type="keyword" />
                <field name="page.store_id" type="integer" />
                <field name="page.title" type="keyword" />
                <field name="page.url" type="keyword" />
                
                <!-- Page data (type) -->
                <field name="page.type.identifier" type="keyword" />
                <field name="page.type.label" type="keyword" />
                
                <!-- Page data (category) -->
                <field name="page.category.id" type="integer" />
                <field name="page.category.label" type="keyword" />
                <field name="page.category.path" type="keyword" />
                
                <!-- Page data (cart) -->
                <field name="page.cart.product_id" type="integer" />
                
                <!-- Page data (product) -->
                <field name="page.product.id" type="integer" />
                <field name="page.product.sku" type="text">
                    <isSearchable>true</isSearchable>
                    <defaultSearchAnalyzer>whitespace</defaultSearchAnalyzer>
                </field>
                <field name="page.product.label" type="text">
                    <isSearchable>true</isSearchable>
                </field>
                
                <!-- Page data (product list) -->
                <field name="page.product_list.current_page" type="integer" />
                <field name="page.product_list.page_count" type="integer" />
                <field name="page.product_list.product_count" type="integer" />
                <field name="page.product_list.display_mode" type="keyword" />
                <field name="page.product_list.sort_order" type="keyword" />
                <field name="page.product_list.sort_direction" type="keyword" />
                <field name="page.product_list.filters.name" type="keyword" nestedPath="page.product_list.filters" />
                <field name="page.product_list.filters.value" type="keyword" nestedPath="page.product_list.filters" />
                
                <!-- Page data (searches) -->
                <field name="page.search.query" type="text">
                    <isSearchable>true</isSearchable>
                    <isUsedForSortBy>true</isUsedForSortBy>
                </field>
                <field name="page.search.is_spellchecked" type="boolean" />
                
                <!-- Page data (CMS) -->
                <field name="page.cms.identifier" type="text">
                    <isSearchable>true</isSearchable>
                </field>
                <field name="page.cms.title" type="text">
                    <isSearchable>true</isSearchable>
                </field>
                
                <!-- Page data (order) -->
                <field name="page.order.grand_total" type="double" />
                <field name="page.order.discount_total" type="double" />
                <field name="page.order.shipping_total" type="double" />
                <field name="page.order.subtotal" type="double" />
                <field name="page.order.payment_method" type="keyword" />
                <field name="page.order.shipping_method" type="keyword" />
                <field name="page.order.salesrules" type="keyword" />
                <field name="page.order.items.sku" type="keyword" nestedPath="page.order.items" />
                <field name="page.order.items.product_id" type="keyword" nestedPath="page.order.items" />
                <field name="page.order.items.category_ids" type="integer" nestedPath="page.order.items" />
                <field name="page.order.items.label" type="keyword" nestedPath="page.order.items" />
                <field name="page.order.items.price" type="double" nestedPath="page.order.items" />
                <field name="page.order.items.row_total" type="double" nestedPath="page.order.items" />
                <field name="page.order.items.qty" type="double" nestedPath="page.order.items" />
                
                <!-- Page data (referrer) -->
                <field name="page.referrer.domain" type="keyword" />
                <field name="page.referrer.page" type="keyword" />
                
                <!-- Page data (campaign) -->
                <field name="page.utm_source" type="keyword" />
                <field name="page.utm_campaign" type="keyword" />
                <field name="page.utm_medium" type="keyword" />
                <field name="page.utm_term" type="keyword" />
                
                <!-- Page data (resolution) -->
                <field name="page.resolution.x" type="integer" />
                <field name="page.resolution.y" type="integer" />
            </mapping>
        </type>
    </index>

    <index identifier="tracking_log_session" defaultSearchType="session">
        <type name="session" idFieldName="session_id">
            <mapping>
                <field name="session_id" type="keyword"/>
                <field name="start_date" type="date"/>
                <field name="end_date" type="date"/>
                <field name="visitor_id" type="keyword"/>
                <field name="product_view" type="integer" />
                <field name="product_cart" type="integer" />
                <field name="category_view" type="integer" />
                <field name="search_query" type="text">
                    <isSearchable>true</isSearchable>
                </field>
                <field name="search_query_void" type="text">
                    <isSearchable>true</isSearchable>
                    <isUsedForSortBy>true</isUsedForSortBy>
                </field>
                <field name="product_sale" type="integer" />
                <field name="category_sale" type="integer" />
            </mapping>
        </type>
    </index>

</indices>
