=== Smile-SA/elasticsuite/src/module-elasticsuite-core/etc/elasticsuite_search_request.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Smile_ElasticsuiteCore indices configuration validation.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer
 * versions in the future.
 *
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteCore
 * @author    Aurelien FOUCRET <aurelien.foucret@smile.fr>
 * @copyright 2018 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="requests">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="1">
                <xs:element name="request" type="request"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="request">
        <xs:all>
            <xs:element name="filters" type="filtersDefinition" minOccurs="0"/>
        </xs:all>
        <xs:attribute type="xs:string" name="name" use="required" />
        <xs:attribute type="xs:string" name="label" use="required" />
        <xs:attribute type="xs:string" name="index" use="required" />
        <xs:attribute type="xs:string" name="type" use="required" />
        <xs:attribute type="xs:boolean" name="fulltext" use="required" />
    </xs:complexType>

    <xs:complexType name="filtersDefinition">
        <xs:sequence maxOccurs="unbounded" minOccurs="1">
            <xs:element name="filter" type="filterDefinition" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="filterDefinition">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== Smile-SA/elasticsuite/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml
<?xml version="1.0"?>
<!--
/**
 * Smile_ElasticsuiteCatalog search requests configuration.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer
 * versions in the future.
 *
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteCatalog
 * @author    Aurelien FOUCRET <aurelien.foucret@smile.fr>
 * @copyright 2018 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
 -->
<requests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="urn:magento:module:Smile_ElasticsuiteCore:etc/elasticsuite_search_request.xsd">

    <request name="quick_search_container" label="Catalog Product Search" index="catalog_product" type="product" fulltext="true">
        <filters>
            <filter name="stockFilter">Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\Stock</filter>
            <filter name="visibleInSearch">Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\VisibleInSearch</filter>
            <filter name="blacklistedProducts">Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\SearchBlacklist</filter>
        </filters>
    </request>

    <request name="catalog_view_container" label="Category Product View" index="catalog_product" type="product" fulltext="false">
        <filters>
            <filter name="stockFilter">Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\Stock</filter>
            <filter name="visibleInCatalog">Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\VisibleInCatalog</filter>
        </filters>
    </request>

    <request name="category_search_container" label="Catalog Category Search" index="catalog_category" type="category" fulltext="true"/>

</requests>
